# Generated by Django 3.1.5 on 2021-01-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
